pub const EXAMPLES: &[&str] = &[
    "SELECT 1 AS some_number,\n\ttrue AS is_true,\n\t'hello' AS greeting,\n\t3.1415 AS pi;",
    "-- PRIMARY KEY is an alias for UNIQUE NOT NULL\nCREATE TABLE IF NOT EXISTS users (\n\tid UINT PRIMARY KEY,\n\tname TEXT,\n\temail TEXT,\n\tpassword TEXT\n);",
    "INSERT INTO users VALUES\n(1, 'John Doe', 'example@email.com', 'password'),\n(2, 'Jane Doe', 'example2@email.com', 'password');",
    "SELECT name, id FROM users;",
    "SELECT * FROM users\nWHERE id < 2;",
    "SELECT * FROM users\nWHERE id = 1\n\tOR name = 'Jane Doe';",
    "-- PREWHERE forces an index search\n-- Can also do ranges\n-- Index is automatically created on UNIQUE columns\nSELECT * FROM users PREWHERE (id BETWEEN 1 AND 2);",
    "CREATE TABLE IF NOT EXISTS addresses (\n\tuser_id UINT,\n\taddress TEXT,\n\tactive BOOL\n);",
    "INSERT INTO addresses(active, user_id, address) VALUES\n(true, 1, '123 Main St'),\n(false, 1, '456 Elm St'),\n(true, 2, '789 Oak St');",
     "-- Begin a transaction, insert data, and commit the changes\nBEGIN;\nINSERT INTO users VALUES (3, 'Alice', 'alice@email.com', 'password');\nINSERT INTO addresses(active, user_id, address) VALUES (true, 3, '321 Maple St');\nCOMMIT;",
    "-- Begin a transaction, insert data, then rollback the changes\nBEGIN;\nINSERT INTO users VALUES (4, 'Bob', 'bob@email.com', 'password');\nINSERT INTO addresses(active, user_id, address) VALUES (true, 4, '654 Pine St');\nROLLBACK;",
    "-- Union\nSELECT id FROM users\nUNION\nSELECT user_id FROM addresses;",
    "-- EXPLAIN shows the query plan without executing it\n-- ANALYZE executes the plan and times it\nEXPLAIN ANALYZE SELECT address\nFROM users\nINNER JOIN addresses\n\tON id = user_id\nWHERE active\nLIMIT 1 OFFSET 1;",
    "UPDATE addresses\nSET address = '123 Main St'\nWHERE user_id = 2;",
    "DELETE FROM addresses\nWHERE user_id <= 1;",
    "DELETE FROM users\nWHERE id = 1;",
    "TRUNCATE TABLE users, addresses;",
    "-- This is a read-only table\nSELECT * from __CATALOG__;",
    "DROP TABLE IF EXISTS users, addresses;",
];
